In [0]:
https://forms.gle/r2ZEPwZrKA5FQzxN7

https://forms.gle/r2ZEPwZrKA5FQzxN7

In [0]:
import pandas as pd
from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

In [0]:
worksheet = gc.open('Sorteo remera Pycon (Responses)').sheet1

rows = worksheet.get_all_values()

In [46]:
df  = pd.DataFrame.from_records(rows[1:])
df = df.rename(columns={0:'ingreso',1:'nombre',2:'numero'})
df['ingreso'] = pd.to_datetime(df['ingreso'])
df['numero'] = pd.to_numeric(df['numero'])
df

               ingreso       nombre  numero
0  2019-04-27 16:17:33        Pablo   0.559
1  2019-04-27 16:19:17       Alvaro   0.000
2  2019-04-27 16:19:19        Ariel   1.000
3  2019-04-27 16:20:15    Nicolas14   0.250
4  2019-04-27 16:20:45        Julio   0.370
5  2019-04-27 16:21:08        Favio   0.800
6  2019-04-27 16:21:19        Renso   0.670
7  2019-04-27 16:22:07      Gessica   0.500
8  2019-04-27 16:22:08        Luigy   0.000
9  2019-04-27 16:22:09       Hunter   1.000
10 2019-04-27 16:22:20      Claudia   0.200
11 2019-04-27 16:23:20        Brian   0.000
12 2019-04-27 16:24:15  Juanchoam26   0.000
13 2019-04-27 16:24:36  Lautaro Rua   1.000
14 2019-04-27 16:26:28  Lautaro Rua   0.000
15 2019-04-27 16:26:59      Mariana   0.200
16 2019-04-27 16:27:23       Abasto   1.000
17 2019-04-27 16:27:40       Abasto   0.000
18 2019-04-27 16:27:49       Marcos   0.290
19 2019-04-27 16:28:17       Mariaz   0.670

In [0]:
from random import random
import numpy as np
import altair as alt

nro_random = random()

In [51]:
ch = alt.Chart(df)
ch.mark_point().encode(x='nombre:N',y='numero:Q').interactive()
# alt.Chart()

Chart({
  data:                ingreso       nombre  numero
  0  2019-04-27 16:17:33        Pablo   0.559
  1  2019-04-27 16:19:17       Alvaro   0.000
  2  2019-04-27 16:19:19        Ariel   1.000
  3  2019-04-27 16:20:15    Nicolas14   0.250
  4  2019-04-27 16:20:45        Julio   0.370
  5  2019-04-27 16:21:08        Favio   0.800
  6  2019-04-27 16:21:19        Renso   0.670
  7  2019-04-27 16:22:07      Gessica   0.500
  8  2019-04-27 16:22:08        Luigy   0.000
  9  2019-04-27 16:22:09       Hunter   1.000
  10 2019-04-27 16:22:20      Claudia   0.200
  11 2019-04-27 16:23:20        Brian   0.000
  12 2019-04-27 16:24:15  Juanchoam26   0.000
  13 2019-04-27 16:24:36  Lautaro Rua   1.000
  14 2019-04-27 16:26:28  Lautaro Rua   0.000
  15 2019-04-27 16:26:59      Mariana   0.200
  16 2019-04-27 16:27:23       Abasto   1.000
  17 2019-04-27 16:27:40       Abasto   0.000
  18 2019-04-27 16:27:49       Marcos   0.290
  19 2019-04-27 16:28:17       Mariaz   0.670,
  encoding: EncodingWithFacet({
    x: X({
      shorthand: 'nombre:N'
    }),
    y: Y({
      shorthand: 'numero:Q'
    })
  }),
  mark: 'point',
  selection: SelectionMapping({
    selector001: SelectionDef({
      bind: 'scales',
      encodings: ['x', 'y'],
      type: 'interval'
    })
  })
})

In [0]:
# df = df[df.numero != 1]

In [62]:
nro_random = random()
df['distancia'] = np.abs( df['numero'] - nro_random )
df.sort_values('distancia').iloc[0]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

ingreso      2019-04-27 16:21:19
nombre                     Renso
numero                      0.67
distancia              0.0331075
Name: 6, dtype: object