[Issue](https://github.com/pandas-dev/pandas/issues/19136)

[Solution](https://stackoverflow.com/questions/34901708/typeerror-cannot-append-a-non-category-item-to-a-categoricalindex)

In [0]:
import pandas as pd

In [9]:
test = pd.DataFrame({
      "a": pd.Series(["a_1", "a_2"], dtype = "category"),
      "b": pd.Series(["b_1", "b_2"], dtype = "category")
  })

problem = test.groupby(["a", "b"]).size().unstack(1)
problem




def reset_index(df):
  "Returns DataFrame with index as columns"
  '''
  Parameters
  ----------
  df DataFrame
  
  Returns
  ------
  
  '''
  index_df = df.index.to_frame(index=False)
  df = df.reset_index(drop=True)
  
  return pd.merge(index_df,df,left_index=True,right_index=True)

print(problem)
solved = reset_index(problem)
print(solved)
solved.info()
solved.to_html()

b    b_1  b_2
a
a_1  1.0  NaN
a_2  NaN  1.0
     a  b_1  b_2
0  a_1  1.0  NaN
1  a_2  NaN  1.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
a      2 non-null category
b_1    1 non-null float64
b_2    1 non-null float64
dtypes: category(1), float64(2)
memory usage: 210.0 bytes

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>a</th>\n      <th>b_1</th>\n      <th>b_2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>a_1</td>\n      <td>1.0</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>a_2</td>\n      <td>NaN</td>\n      <td>1.0</td>\n    </tr>\n  </tbody>\n</table>'

In [19]:
!pip install tabulate
from tabulate import tabulate
print(tabulate(problem,headers='firstrow', tablefmt='pipe'))

| a_1   |   1.0 |   nan |
|:------|------:|------:|
| a_2   |   nan |     1 |

In [15]:
reset_index()

b    b_1  b_2
a
a_1  1.0  NaN
a_2  NaN  1.0